### ISSUE TITLE
De-barking causes game crash

### ISSUE THREAD

**Issue by Rivallrelyks** [HollywoodHeists/public#125]
at least once a run while using the dark area at logging it will cause and instant game crash with no warnings error codes or alerts.

**Comment by MrKyRy** [comment]
I was testing this and I believe it crashed because people are debarking too quickly. I started to do only 4 logs at a time and have had zero crashes. Ill cut 4 logs and debark them and then turn them to paper. I have not had an issue or crashing while doing this format. Whenever I would try for 8 or 10 I would crash on the 6th log every time.

**Comment by Montana-77** [comment]
Thank you for the details on this bug.   This one has been tricky and we are still working on a solution!

**Comment by AliAliJr** [comment]
Fixed.
