### ISSUE TITLE
Crime is too high risk for low rewards.

### ISSUE THREAD

**Issue by Pigglesworrth** [HollywoodHeists/public#165]
On average, it seems (for store robberies) Risk is way too high, for little reward. I make about 1,500 Give or take a few hundred, That coupled with the cooldown of 10 minutes. (without the cooldown I used to make a decent amount of money worth the risk) makes doing legals not only safer but more profitable. Also I have noticed Most of the crime done is by me. Of course one of the main reasons I do it is because it is fun and I know the cops get bored when nothing happens. but I just don't see how I am supposed to keep making it fun while doing crime when I have a bunch of fines. it just seems like a lose lose for any crim.

**Comment by CloudCasanova** [comment]
We are continuously tweaking fines so that they are fair and have a good risk vs reward structure. We actually just did an entire overhaul to lower fines AND times. You do not do most of the crime and you do not need to "entertain" police because they "get bored." We love to encourage crime but you having a bunch of fines is on you. You didn't plan to get away adequately, most of the time don't have a hostage and more or less just execute said robberies poorly. Roleplaying isn't just running around to smash and grab loot. Its an economy, you are responsible for the fines you gather while committing said crimes. There are plenty of other ways in the city to make money and pay off said fines, they actually just added a couple new legal jobs yesterday! If you like doing crime and its fun, you need to find ways to fund it on your own.

**Comment by ItsTrihawk** [comment]
Don't just go crazy with robberies, plenty of other criminal activities you can do as well. Crime shouldn't be cheap it should be balanced. Go explore, make connections, and expand your rp story, no need to only feel like you need to entertain others.

**Comment by Pigglesworrth** [comment]
Fair enough. Thanks for response.
