### ISSUE TITLE
Used Car lot

### ISSUE THREAD

**Issue by cvalenta44** [HollywoodHeists/public#215]
So I noticed that the sell back to city price is 50%, I'll be honest I think a better percentage would be 66%-75%. My assumption is that the 50% was put in place so people would list their vehicles on the car lot so people can buy it but at the moment UCL is very not visited and vehicles get listed stay there for a while.

**Comment by Midori33** [comment]
i think that this could be a great jumping off point to start looking in to player owned used car dealerships. i know it was brought up at the town hall but i think having it so that the owner or sales person has to be around for you to sell your car to the dealership and then the car can be parked in the lot with like a "buy now" price. However, if someone from the dealership is in city, you can meet with them and perhaps negotiate on a lower price.

**Comment by cvalenta44** [comment]
I honestly really like that idea was thinking about it last night, there's a complete interior already for the otto's dealership but there is also Auto Exotic that could be used (MLO https://as-mlo.tebex.io/package/5368837 )

**Comment by Colt-Sterling** [comment]
I like the idea of someone who's around to sell cars, but I'm also not against bumping up the percentage for a little while just so it doesn't hurt so much to sell an old car 👍

**Comment by AliAliJr** [comment]
Changed to 75%.
