### ISSUE TITLE
Car Boosting

### ISSUE THREAD

**Issue by ItsLoftus** [HollywoodHeists/public#218]
2 of us did car boosting last night and it was honestly embarrassing, the cars that we get offered are actually so bad that its debateable on whether we want to take chase in them or not. They barely move at all and we had literally every officer online (around 7-8) on our cases tag teaming out to get fuel and repairs. If we are only allowed 4 in a crime then shouldn't there be a limit on how many officers get involved in the scene. With how bad the cars are  that get boosted and the amount of police that where involved there was definitely no chance at all that we would pull it off successfully. Is there chance that we get better cars with better engines or that less police get involved, the chases are fun don't get me wrong but it makes it less fun when you know there is no chance of evading at all.

**Comment by ChugThis** [comment]
Car boosting should have some kind of grading system for sure. Should know what kind of car your getting yourselves into. I only saw a part of one of the chases, I think the very beginning of the grey pick-up? I know there was a charger chasing that broke off because of the difference in car type, should have had only tahoes and CVPI’s on you. We do have a limit on officers attached to crimes, in the future we will be MUCH better about officers attached. Gas is something imo should get looked at increasing, because if an officer patrols for 3 minutes they will generally be down to half a tank. If an officer requires repairs they are not allowed back on the chase. We have limits for all crimes on how many should attach. Unfortunately right now it’s a little of “everyone wants to attach because it’s something to do”. But what I can do is create a harder set rule for officers to follow on attaching to crimes, chases etc… 
I can only comment on LEO response which we are still working on, and will adjust

**Comment by ItsLoftus** [comment]
The first boost went great, i think there was only 3 on it that i can recall and the chance of getting caught and getting away was pretty equal, the second boost was just an impossible situation and i totally get that everyone wants a piece of the action when there isn't much crime going on so i completely understand that, it was just impossible to do anything in a car that barely moved with the amount of police that where actively chasing. Not a huge issue i know, but i personally think a better car would provide a better chase

**Comment by Meelokbruvv** [comment]
So it my knowledge (I may be wrong) but boosting goes off of a experience system so of your just starting out the cars your getting may be crappyish cause of being new to it but after so many cars I believe your supposed to "level up" to better cars I may be wrong so don't take my word for it

**Comment by ItsLoftus** [comment]
I honestly don't know how it works, im just usually the back up driver and there for the pickups when they get dropped off. This was only the second one i ever did

**Comment by ChugThis** [comment]
As far as the specifics of how the crime works I have no knowledge, but can and will adjust LEO response for it. All a learning curve. Thanks for bringing this to our attention

**Comment by Bergsbrew** [comment]
Car boosting is a experience based thing. The more boosts you do the more experience, the better the cars. This system will be changing soon however and the quality of the car might be more obvious with the new system. LEO are not allowed to repair and rejoin the chase, however getting gas and regaining is absolutely something that happens. If youd like to talk more about that boost feel free to dm me, as I can give more insight to LEO sides of things since I was apart of the chase.

**Comment by AliAliJr** [comment]
^
