### ISSUE TITLE
Oxy Runs

### ISSUE THREAD

**Issue by K-Reynolds** [HollywoodHeists/public#63]
Hey there, just sharing my concerns around the Oxy runs.

They take 1k to do, for 5 boxes weighing 40 each, then you go drop them off at a location. Here are my concerns.
- Each box gets you somewhat between 200 and 300$ which just barely covers the initial price + gas needed.
- You hardly get any Oxy. I've done a few runs yesterday and only ended up with 5.
- The spots in which to wait for the ped car are very tricky to get, I stood in the places almost 5 minutes sometimes figuring out with exact spot there was gonna trigger the script. Making the area a tad larger might be good.

Overall its quite an investment, and quite the risk for hardly any reward at all, or so it feels to me. I understand crim stuff needs to be a lil extra hard but it should also pay off a little more, but it doesn't feel that way to me atm.

Any other perspectives and opinions appreciated of course, I just wanted to point it out ♡.

K

**Comment by Montana-77** [comment]
Thank you for the feedback this helps a ton! We cut the initial cost in half. also buffed the payout. This will take affect at next restart. Will run more of them and monitor this thread.  Also going to test the trigger's and see if we can enlarge them. TY

**Comment by KosimaGhost** [comment]
Thanks a lot for the swift reply, that's good to hear. I did then start wondering if the cars don't come on a timer because if I had to wait around before going to the spot for whatever reason, the car would already be parked there. Unsure but thought that might be helpful.

I'm looking forward to leep trying it out :).

(oops wrong account sorry, it's K though.)
