### ISSUE TITLE
current economic system

### ISSUE THREAD

**Issue by BigTony7** [HollywoodHeists/public#80]
I’m writing this from my own experience and I don’t want to sound like I’m complaining about the city itself, but I think the current economy might need to change for now due to how new the city is. 
The whitelisted jobs are very low paying from what I’ve noticed—I understand the city is new and as a new player you wouldn’t want “grinding” jobs as the sole job available to you.  We should either increase the payouts or decrease the cost of cars. It would be more beneficial to all if more product is available within the city. 
People would tell their friends, who would share with their friends, resulting in more people entering the city.  Once more people populate the server, you could start increasing the value of things.  Most people come home from work IRL and only have a certain about amount of time to grind before actual RP’ng happens. 
They would rather have some time were they do nothing but grind for decent money then start having fun RP’ng with everyone. This wouldn’t necessarily be a major change, but enough to retain current players and bring in new ones for more RP in PD, EMS, Burger Shot etc. 
Instead of solely relying on the casino to make decent money, player owned shops with better payouts would help keep workers and entice people to own a thriving business.

**Comment by Midori33** [comment]
While I think the economy could probably use a boost, I also think that adding vehicle financing may help this situation. Not sure if that has already been talked about but at least that way you wouldn't need as much to put down to initially get the vehicle but would still need to be able to work to get it paid off.

**Comment by RockemRobotics** [comment]
Personal opinion - People should have to put time in to the city before they can afford high end cars. It's been less than a week since the big reset happened, so I wouldn't expect anyone to be able to afford the high-end supercars, not yet anyway.  It gives something to work towards long term in the background of all the RP.

Plenty of RP can happen even with low-end cars, too. Heck, you can have a great police chase while escaping on a BMX bike.

**Comment by BigTony7** [comment]
I 100% agree, I think a city with nothing but high end cars isn't really fun especially for cops because in all honesty who the hell waste 2.3 mill on a Lamborghini to run from the cops. From what I've gathered even to buy a low end car less than 70k you have to out more than 10 hours to afford something along those lines, the jobs now pay out less than 5k an hour and no one really wants to spend more than 10 hours to buy a car, I believe the financing option is a good idea too with just a boost to the payouts, work a couple jobs, put a down payment, get your car do whatever then go back to work and pay the car off. And again this shouldn't be a permanent thing just until more people come in and then you could lower payouts or the cost of cars, guns, etc.

**Comment by ItsTrihawk** [comment]
I'd like to add onto this. I don't mind the price of cars, those are just cosmetic items to an extent. The issue I have currently in the economy is the cost of living. With the wages offered to leo's specifically speaking from experience, is that youre living wage will never allow for you to bolster your savings. Let me explain. as a cadet you are payed 500 dollars a month, or hour, however you view it. At officer one you make about 1400 an hour/month. These wages are alot of times spent on gas and food, about 1000 a hour/month. leaving 400 profit margin. The current gas fill up station at mrpd only sales jerry cans to me, and for RP purposes, we like to fill up in the field for the possibility to interact and rp with others. From the civ side I can tell there could be a similar construct and a very large "grind" aspect to the city. Do I believe that there should be cheaper cars? well if you ask me there could be balancing BUT I don't think it's at an overwhelming unhealthy state since there are affordable cars. I do however think the cost of living is crazy expensive, and leaves such little room for those with salary jobs to enjoy any off time that isn't filled with "grinding" legals.

**Comment by YouTri** [comment]
I agree with this.  It definitely needs a change for now. Cars before launch were in a decent state{Price wise}. The payouts definitely needs a raise.  Wages arent livable with the fact Stress is crazy. If i want an interaction at player owned places thats extra 100-400 bucks from what ive seen. Overall there needs a change.

**Comment by Montana-77** [comment]
Complete Economy Update will be pushed through by the weekend.. this entails small buffs to all legals, WL, and crim side
